### ISSUE TITLE
Responsive Support

### ISSUE THREAD

**Issue by unhang** [unhang/game-jumping-crew#28]
## Todo 1:

<img width="1078" alt="Screen Shot 2020-09-20 at 16 34 41" src="https://user-images.githubusercontent.com/48117315/93708363-b2e46980-fb5f-11ea-9d32-1055c76188f6.png">

### Acceptance Criteria
- [ ] 1 font nhỏ lại, vừa trên 1 line
- [ ] 2 font nhỏ lại, line-height giảm bớt, vừa phải
- [ ] button display as 100% block on mobile

## Todo 2:

![image](https://user-images.githubusercontent.com/48117315/93708411-0fe01f80-fb60-11ea-9612-70459eb8c4e1.png)

### Acceptance Criteria
- [ ] mỗi cột trên PC sẽ là chiếm full 100% trên mobile

## Todo 3:

<img width="377" alt="Screen Shot 2020-09-20 at 16 42 38" src="https://user-images.githubusercontent.com/48117315/93708435-63526d80-fb60-11ea-9c85-fc8efa0d5ad6.png">

### Acceptance Criteria
- [ ] 1. khi ko có imge url, hiển thị ảnh mặc đinh => nếu url ko load được ảnh chỉ hiển thị ảnh mặc định
- [ ] 2. Giảm font size, cỡ 14 ~ 16px, tuỳ chỉnh phù hợp
